apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: production

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: ENVIRONMENT
          value: production
  target:
    kind: Deployment
    name: my-app
resources:
- ../../base
images:
- name: my-app
  newName: 539536562581.dkr.ecr.us-east-1.amazonaws.com/my-app
  newTag: a001c7704f0246cfe8b2514698a7389f97b2ad1d
